const path = require("path");
const connect = require("./connect");
const fs = require('fs');

function readJSONFile() {
    const data = fs.readFileSync(path.join(__dirname, "..", "movies.json"), 'utf8');
    const dataLines = data.split("\n");
    for (let i = 0; i < 10; i++) {
        console.log(dataLines[i]);
        console.log("-------------------------------------------------------");            
    }
}

createCollections = async () => {
    const { db, client} = await connect();
    var insertResult;
    try {
        const moviesCollection = db.collection("movies");
        const docs = [
            {"plot":"Three men hammer on an anvil and pass a bottle of beer around.","genres":["Short"],"runtime":{"$numberInt":"1"},"cast":["Charles Kayser","John Ott"],"num_mflix_comments":{"$numberInt":"1"},"title":"Blacksmith Scene","fullplot":"A stationary camera looks at a large anvil with a blacksmith behind it and one on either side. The smith in the middle draws a heated metal rod from the fire, places it on the anvil, and all three begin a rhythmic hammering. After several blows, the metal goes back in the fire. One smith pulls out a bottle of beer, and they each take a swig. Then, out comes the glowing metal and the hammering resumes.","countries":["USA"],"released":{"$date":{"$numberLong":"-2418768000000"}},"directors":["William K.L. Dickson"],"rated":"UNRATED","awards":{"wins":{"$numberInt":"1"},"nominations":{"$numberInt":"0"},"text":"1 win."},"lastupdated":"2015-08-26 00:03:50.133000000","year":{"$numberInt":"1893"},"imdb":{"rating":{"$numberDouble":"6.2"},"votes":{"$numberInt":"1189"},"id":{"$numberInt":"5"}},"type":"movie","tomatoes":{"viewer":{"rating":{"$numberInt":"3"},"numReviews":{"$numberInt":"184"},"meter":{"$numberInt":"32"}},"lastUpdated":{"$date":{"$numberLong":"1435516449000"}}}},
            {"plot":"A group of bandits stage a brazen train hold-up, only to find a determined posse hot on their heels.","genres":["Short","Western"],"runtime":{"$numberInt":"11"},"cast":["A.C. Abadie","Gilbert M. 'Broncho Billy' Anderson","George Barnes","Justus D. Barnes"],"poster":"https://m.media-amazon.com/images/M/MV5BMTU3NjE5NzYtYTYyNS00MDVmLWIwYjgtMmYwYWIxZDYyNzU2XkEyXkFqcGdeQXVyNzQzNzQxNzI@._V1_SY1000_SX677_AL_.jpg","title":"The Great Train Robbery","fullplot":"Among the earliest existing films in American cinema - notable as the first film that presented a narrative story to tell - it depicts a group of cowboy outlaws who hold up a train and rob the passengers. They are then pursued by a Sheriff's posse. Several scenes have color included - all hand tinted.","languages":["English"],"released":{"$date":{"$numberLong":"-2085523200000"}},"directors":["Edwin S. Porter"],"rated":"TV-G","awards":{"wins":{"$numberInt":"1"},"nominations":{"$numberInt":"0"},"text":"1 win."},"lastupdated":"2015-08-13 00:27:59.177000000","year":{"$numberInt":"1903"},"imdb":{"rating":{"$numberDouble":"7.4"},"votes":{"$numberInt":"9847"},"id":{"$numberInt":"439"}},"countries":["USA"],"type":"movie","tomatoes":{"viewer":{"rating":{"$numberDouble":"3.7"},"numReviews":{"$numberInt":"2559"},"meter":{"$numberInt":"75"}},"fresh":{"$numberInt":"6"},"critic":{"rating":{"$numberDouble":"7.6"},"numReviews":{"$numberInt":"6"},"meter":{"$numberInt":"100"}},"rotten":{"$numberInt":"0"},"lastUpdated":{"$date":{"$numberLong":"1439061370000"}}}},
            {"plot":"A young boy, opressed by his mother, goes on an outing in the country with a social welfare group where he dares to dream of a land where the cares of his ordinary life fade.","genres":["Short","Drama","Fantasy"],"runtime":{"$numberInt":"14"},"rated":"UNRATED","cast":["Martin Fuller","Mrs. William Bechtel","Walter Edwin","Ethel Jewett"],"num_mflix_comments":{"$numberInt":"2"},"poster":"https://m.media-amazon.com/images/M/MV5BMTMzMDcxMjgyNl5BMl5BanBnXkFtZTcwOTgxNjg4Mg@@._V1_SY1000_SX677_AL_.jpg","title":"The Land Beyond the Sunset","fullplot":"Thanks to the Fresh Air Fund, a slum child escapes his drunken mother for a day's outing in the country. Upon arriving, he and the other children are told a story about a mythical land of no pain. Rather then return to the slum at day's end, the lad seeks to journey to that beautiful land beyond the sunset.","languages":["English"],"released":{"$date":{"$numberLong":"-1804377600000"}},"directors":["Harold M. Shaw"],"writers":["Dorothy G. Shore"],"awards":{"wins":{"$numberInt":"1"},"nominations":{"$numberInt":"0"},"text":"1 win."},"lastupdated":"2015-08-29 00:27:45.437000000","year":{"$numberInt":"1912"},"imdb":{"rating":{"$numberDouble":"7.1"},"votes":{"$numberInt":"448"},"id":{"$numberInt":"488"}},"countries":["USA"],"type":"movie","tomatoes":{"viewer":{"rating":{"$numberDouble":"3.7"},"numReviews":{"$numberInt":"53"},"meter":{"$numberInt":"67"}},"lastUpdated":{"$date":{"$numberLong":"1430161595000"}}}},
            {"plot":"A greedy tycoon decides, on a whim, to corner the world market in wheat. This doubles the price of bread, forcing the grain's producers into charity lines and further into poverty. The film...","genres":["Short","Drama"],"runtime":{"$numberInt":"14"},"cast":["Frank Powell","Grace Henderson","James Kirkwood","Linda Arvidson"],"num_mflix_comments":{"$numberInt":"1"},"title":"A Corner in Wheat","fullplot":"A greedy tycoon decides, on a whim, to corner the world market in wheat. This doubles the price of bread, forcing the grain's producers into charity lines and further into poverty. The film continues to contrast the ironic differences between the lives of those who work to grow the wheat and the life of the man who dabbles in its sale for profit.","languages":["English"],"released":{"$date":{"$numberLong":"-1895097600000"}},"directors":["D.W. Griffith"],"rated":"G","awards":{"wins":{"$numberInt":"1"},"nominations":{"$numberInt":"0"},"text":"1 win."},"lastupdated":"2015-08-13 00:46:30.660000000","year":{"$numberInt":"1909"},"imdb":{"rating":{"$numberDouble":"6.6"},"votes":{"$numberInt":"1375"},"id":{"$numberInt":"832"}},"countries":["USA"],"type":"movie","tomatoes":{"viewer":{"rating":{"$numberDouble":"3.6"},"numReviews":{"$numberInt":"109"},"meter":{"$numberInt":"73"}},"lastUpdated":{"$date":{"$numberLong":"1431369413000"}}}},
            {"plot":"Cartoon figures announce, via comic strip balloons, that they will move - and move they do, in a wildly exaggerated style.","genres":["Animation","Short","Comedy"],"runtime":{"$numberInt":"7"},"cast":["Winsor McCay"],"num_mflix_comments":{"$numberInt":"1"},"poster":"https://m.media-amazon.com/images/M/MV5BYzg2NjNhNTctMjUxMi00ZWU4LWI3ZjYtNTI0NTQxNThjZTk2XkEyXkFqcGdeQXVyNzg5OTk2OA@@._V1_SY1000_SX677_AL_.jpg","title":"Winsor McCay, the Famous Cartoonist of the N.Y. Herald and His Moving Comics","fullplot":"Cartoonist Winsor McCay agrees to create a large set of drawings that will be photographed and made into a motion picture. The job requires plenty of drawing supplies, and the cartoonist must also overcome some mishaps caused by an assistant. Finally, the work is done, and everyone can see the resulting animated picture.","languages":["English"],"released":{"$date":{"$numberLong":"-1853539200000"}},"directors":["Winsor McCay","J. Stuart Blackton"],"writers":["Winsor McCay (comic strip \"Little Nemo in Slumberland\")","Winsor McCay (screenplay)"],"awards":{"wins":{"$numberInt":"1"},"nominations":{"$numberInt":"0"},"text":"1 win."},"lastupdated":"2015-08-29 01:09:03.030000000","year":{"$numberInt":"1911"},"imdb":{"rating":{"$numberDouble":"7.3"},"votes":{"$numberInt":"1034"},"id":{"$numberInt":"1737"}},"countries":["USA"],"type":"movie","tomatoes":{"viewer":{"rating":{"$numberDouble":"3.4"},"numReviews":{"$numberInt":"89"},"meter":{"$numberInt":"47"}},"lastUpdated":{"$date":{"$numberLong":"1440096684000"}}}},
            {"plot":"A woman, with the aid of her police officer sweetheart, endeavors to uncover the prostitution ring that has kidnapped her sister, and the philanthropist who secretly runs it.","genres":["Crime","Drama"],"runtime":{"$numberInt":"88"},"cast":["Jane Gail","Ethel Grandin","William H. Turner","Matt Moore"],"num_mflix_comments":{"$numberInt":"2"},"poster":"https://m.media-amazon.com/images/M/MV5BYzk0YWQzMGYtYTM5MC00NjM2LWE5YzYtMjgyNDVhZDg1N2YzXkEyXkFqcGdeQXVyMzE0MjY5ODA@._V1_SY1000_SX677_AL_.jpg","title":"Traffic in Souls","lastupdated":"2015-09-15 02:07:14.247000000","languages":["English"],"released":{"$date":{"$numberLong":"-1770508800000"}},"directors":["George Loane Tucker"],"rated":"TV-PG","awards":{"wins":{"$numberInt":"1"},"nominations":{"$numberInt":"0"},"text":"1 win."},"year":{"$numberInt":"1913"},"imdb":{"rating":{"$numberInt":"6"},"votes":{"$numberInt":"371"},"id":{"$numberInt":"3471"}},"countries":["USA"],"type":"movie","tomatoes":{"viewer":{"rating":{"$numberInt":"3"},"numReviews":{"$numberInt":"85"},"meter":{"$numberInt":"57"}},"dvd":{"$date":{"$numberLong":"1219708800000"}},"lastUpdated":{"$date":{"$numberLong":"1439231635000"}}}},
            {"plot":"The cartoonist, Winsor McCay, brings the Dinosaurus back to life in the figure of his latest creation, Gertie the Dinosaur.","genres":["Animation","Short","Comedy"],"runtime":{"$numberInt":"12"},"cast":["Winsor McCay","George McManus","Roy L. McCardell"],"num_mflix_comments":{"$numberInt":"1"},"poster":"https://m.media-amazon.com/images/M/MV5BMTQxNzI4ODQ3NF5BMl5BanBnXkFtZTgwNzY5NzMwMjE@._V1_SY1000_SX677_AL_.jpg","title":"Gertie the Dinosaur","fullplot":"Winsor Z. McCay bets another cartoonist that he can animate a dinosaur. So he draws a big friendly herbivore called Gertie. Then he get into his own picture. Gertie walks through the picture, eats a tree, meets her creator, and takes him carefully on her back for a ride.","languages":["English"],"released":{"$date":{"$numberLong":"-1745020800000"}},"directors":["Winsor McCay"],"writers":["Winsor McCay"],"awards":{"wins":{"$numberInt":"1"},"nominations":{"$numberInt":"0"},"text":"1 win."},"lastupdated":"2015-08-18 01:03:15.313000000","year":{"$numberInt":"1914"},"imdb":{"rating":{"$numberDouble":"7.3"},"votes":{"$numberInt":"1837"},"id":{"$numberInt":"4008"}},"countries":["USA"],"type":"movie","tomatoes":{"viewer":{"rating":{"$numberDouble":"3.7"},"numReviews":{"$numberInt":"29"}},"lastUpdated":{"$date":{"$numberLong":"1439234403000"}}}},
            {"plot":"Original advertising for the film describes it as a drama of primitive life on the shores of the North Pacific...","genres":["Drama","History"],"runtime":{"$numberInt":"65"},"cast":["Stanley Hunt","Sarah Constance Smith Hunt","Mrs. George Walkus","Paddy 'Malid"],"num_mflix_comments":{"$numberInt":"1"},"poster":"https://m.media-amazon.com/images/M/MV5BMjE3MjAyNzM5NV5BMl5BanBnXkFtZTgwMjA5OTg5NjE@._V1_SY1000_SX677_AL_.jpg","title":"In the Land of the Head Hunters","lastupdated":"2015-09-16 12:11:37.770000000","languages":["English"],"released":{"$date":{"$numberLong":"-1737849600000"}},"directors":["Edward S. Curtis"],"writers":["Edward S. Curtis (story)"],"awards":{"wins":{"$numberInt":"1"},"nominations":{"$numberInt":"0"},"text":"1 win."},"year":{"$numberInt":"1914"},"imdb":{"rating":{"$numberDouble":"5.8"},"votes":{"$numberInt":"223"},"id":{"$numberInt":"4150"}},"countries":["USA"],"type":"movie","tomatoes":{"viewer":{"rating":{"$numberDouble":"2.7"},"numReviews":{"$numberInt":"64"},"meter":{"$numberInt":"18"}},"dvd":{"$date":{"$numberLong":"966297600000"}},"website":"http://www.milestonefilms.com/","production":"World Film Corporation","lastUpdated":{"$date":{"$numberLong":"1439925672000"}}}},
            {"plot":"Young Pauline is left a lot of money when her wealthy uncle dies. However, her uncle's secretary has been named as her guardian until she marries, at which time she will officially take ...","genres":["Action"],"runtime":{"$numberInt":"199"},"cast":["Pearl White","Crane Wilbur","Paul Panzer","Edward Josè"],"num_mflix_comments":{"$numberInt":"1"},"poster":"https://m.media-amazon.com/images/M/MV5BMzgxODk1Mzk2Ml5BMl5BanBnXkFtZTgwMDg0NzkwMjE@._V1_SY1000_SX677_AL_.jpg","title":"The Perils of Pauline","fullplot":"Young Pauline is left a lot of money when her wealthy uncle dies. However, her uncle's secretary has been named as her guardian until she marries, at which time she will officially take possession of her inheritance. Meanwhile, her \"guardian\" and his confederates constantly come up with schemes to get rid of Pauline so that he can get his hands on the money himself.","languages":["English"],"released":{"$date":{"$numberLong":"-1760227200000"}},"directors":["Louis J. Gasnier","Donald MacKenzie"],"writers":["Charles W. Goddard (screenplay)","Basil Dickey (screenplay)","Charles W. Goddard (novel)","George B. Seitz","Bertram Millhauser"],"awards":{"wins":{"$numberInt":"1"},"nominations":{"$numberInt":"0"},"text":"1 win."},"lastupdated":"2015-09-12 00:01:18.647000000","year":{"$numberInt":"1914"},"imdb":{"rating":{"$numberDouble":"7.6"},"votes":{"$numberInt":"744"},"id":{"$numberInt":"4465"}},"countries":["USA"],"type":"movie","tomatoes":{"viewer":{"rating":{"$numberDouble":"2.8"},"numReviews":{"$numberInt":"9"}},"production":"Pathè Frères","lastUpdated":{"$date":{"$numberLong":"1441993579000"}}}},
            {"plot":"The Civil War divides friends and destroys families, but that's nothing compared to the anarchy in the black-ruled South after the war.","genres":["Drama","History","Romance"],"runtime":{"$numberInt":"165"},"rated":"NOT RATED","cast":["Lillian Gish","Mae Marsh","Henry B. Walthall","Miriam Cooper"],"poster":"https://m.media-amazon.com/images/M/MV5BYTM4ZDhiYTQtYzExNC00YjVlLTg2YWYtYTk3NTAzMzcwNTExXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SY1000_SX677_AL_.jpg","title":"The Birth of a Nation","fullplot":"Two brothers, Phil and Ted Stoneman, visit their friends in Piedmont, South Carolina: the family Cameron. This friendship is affected by the Civil War, as the Stonemans and the Camerons must join up opposite armies. The consequences of the War in their lives are shown in connection to major historical events, like the development of the Civil War itself, Lincoln's assassination, and the birth of the Ku Klux Klan.","countries":["USA"],"released":{"$date":{"$numberLong":"-1730419200000"}},"directors":["D.W. Griffith"],"writers":["Thomas Dixon Jr. (adapted from his novel: \"The Clansman: An Historical Romance of the Ku Klux Klan\")","Thomas Dixon Jr. (play)","Thomas Dixon Jr. (novel)","D.W. Griffith","Frank E. Woods"],"awards":{"wins":{"$numberInt":"2"},"nominations":{"$numberInt":"0"},"text":"2 wins."},"lastupdated":"2015-09-11 00:32:27.763000000","year":{"$numberInt":"1915"},"imdb":{"rating":{"$numberDouble":"6.8"},"votes":{"$numberInt":"15715"},"id":{"$numberInt":"4972"}},"type":"movie","tomatoes":{"viewer":{"rating":{"$numberDouble":"3.2"},"numReviews":{"$numberInt":"4358"},"meter":{"$numberInt":"57"}},"dvd":{"$date":{"$numberLong":"1088467200000"}},"critic":{"rating":{"$numberInt":"8"},"numReviews":{"$numberInt":"38"},"meter":{"$numberInt":"100"}},"lastUpdated":{"$date":{"$numberLong":"1441909823000"}},"consensus":"Racial depictions aside, The Birth of a Nation is a landmark film whose achievements and pioneering techniques remain fully relevant today.","rotten":{"$numberInt":"0"},"production":"Gravitas","fresh":{"$numberInt":"38"}}}
        ]
        insertResult = await moviesCollection.insertMany(docs);
        // console.log(insertResult);
    } catch (error) {
        console.error(error);
    } finally {
        await client.close();
    }
    return insertResult;
}

createCollections();